export const emotionDefinitions = {

"consumed by injustice": "Feeling overtaken by anger and moral distress because something feels deeply unfair or violating.",
"incensed": "Very angry because something feels unjust, disrespectful, or morally wrong.",
"livid": "Extremely angry, often when respect, safety, or fairness feels violated.",
"outraged": "Strong anger in response to something that feels morally wrong or unjust.",
"enraged": "At the peak of anger, often connected to perceived violation or threat.",
"repulsed": "Feeling strongly pushed away by something perceived as violating or unsafe.",
"appalled": "Deeply shocked and disturbed by something morally unacceptable.",
"boiling frustration": "Intense frustration when progress feels blocked or obstructed.",
"seething": "Quiet but powerful anger building beneath the surface.",
"fuming": "Hot, active anger often triggered by disrespect or unfairness.",
"indignant": "Anger rooted in a sense of violated fairness or dignity.",
"aggrieved": "Feeling wronged or mistreated and seeking acknowledgment.",
"disgusted": "A strong aversion toward something perceived as offensive or harmful.",
"revolted": "Feeling deeply repelled by something morally or physically disturbing.",
"furious about unfairness": "Intense anger arising specifically from perceived injustice.",
"worked up": "Emotionally stirred and activated, often by unfair treatment.",
"provoked": "Anger triggered by actions that feel disrespectful or violating.",
"resentful": "Lingering anger mixed with hurt when fairness or reciprocity feels absent.",
"irate": "Very angry because something feels disrespectful or unjust.",
"grossed out": "Feeling repelled or uncomfortable with something unpleasant.",
"averse": "Feeling resistant or pushed away from something uncomfortable.",
"frustrated": "Upset because something important feels blocked or slowed.",
"blocked": "Feeling prevented from moving forward toward something important.",
"impeded": "Feeling hindered or obstructed from progress.",
"stuck": "Feeling unable to move forward despite wanting change.",
"halted": "Feeling suddenly stopped in momentum or progress.",
"soured": "A shift toward bitterness or disappointment after expectations changed.",
"disengaged": "Pulling away emotionally when connection or meaning feels absent.",
"agitated": "Internally stirred up and unsettled.",
"irritated": "Mild anger caused by small disruptions or annoyances.",
"bothered": "Feeling mildly upset or disturbed.",
"disturbed": "Emotionally unsettled by something upsetting.",
"disrupted": "Feeling thrown off balance by interruption.",
"ruffled": "Mildly unsettled or emotionally shaken.",
"stirred": "Emotionally activated or moved.",
"activated": "Emotionally and physically aroused or stimulated.",
"slightly activated": "Mild internal alertness or stimulation.",
"quietly braced": "Subtly preparing for something uncertain.",
"held readiness": "A state of quiet preparedness.",
"contained activation": "Energy held internally without outward reaction.",
"internally noisy": "Experiencing many internal thoughts or sensations.",
"internally busy": "Mentally active with many thoughts or considerations.",
"pressured": "Feeling pushed by demands or expectations.",
"compressed": "Feeling constrained or restricted.",
"weighted": "Feeling heavy with responsibility or emotional load.",
"burdened": "Carrying responsibilities or emotional strain.",
"loaded": "Feeling full of demands or pressure.",
"tense": "Physically or emotionally tight and activated.",
"rigid": "Feeling inflexible or tightly controlled.",
"braced": "Prepared for possible difficulty.",
"held tight": "Emotionally or physically constricted.",
"contained": "Holding emotions inwardly without expression.",
"restricted": "Feeling limited in autonomy or freedom.",
"self-monitored": "Closely watching one's own behavior or reactions.",
"shocked": "Suddenly overwhelmed by unexpected information.",
"blindsided": "Caught completely off guard.",
"astonished": "Deeply surprised by something unexpected.",
"stunned": "Momentarily frozen by shock or surprise.",
"surprised": "Experiencing an unexpected shift in expectation.",
"confused": "Lacking clarity about what is happening.",
"disoriented": "Feeling mentally or emotionally lost.",
"uncertain": "Not sure what to expect or believe.",
"puzzled": "Trying to understand something unclear.",
"bewildered": "Feeling overwhelmed by confusion.",
"fearful": "Feeling threatened or unsafe.",
"anxious": "Experiencing worry about possible future problems.",
"worried": "Concerned about potential difficulties.",
"concerned": "Caring about a situation that may require attention.",
"apprehensive": "Uneasy anticipation of something uncertain.",
"guarded": "Protective and cautious about emotional exposure.",
"vigilant": "Closely watching for possible threats.",
"uneasy": "Feeling unsettled or uncomfortable.",
"restless": "Struggling to relax or remain still.",
"urgent": "Feeling pressure to act quickly.",
"reactive": "Quickly responding emotionally to stimuli.",
"alert": "Attentive and aware of surroundings.",
"preoccupied": "Mentally absorbed by thoughts.",
"curious": "Interested in learning or understanding something.",
"sad": "Feeling emotional pain or loss.",
"down": "Experiencing lowered mood or energy.",
"discouraged": "Feeling reduced motivation or hope.",
"heavy-hearted": "Feeling weighed down by sadness.",
"lonely": "Feeling lacking in meaningful connection.",
"heartbroken": "Experiencing deep emotional pain from loss.",
"devastated": "Overwhelmed by grief or emotional loss.",
"despondent": "Feeling hopeless or deeply discouraged.",
"tender": "Emotionally sensitive and open.",
"raw": "Emotionally exposed or vulnerable.",
"fragile": "Feeling easily hurt or overwhelmed.",
"ashamed": "Feeling painful awareness of perceived wrongdoing.",
"embarrassed": "Feeling uncomfortable about social exposure.",
"guilty": "Recognizing harm or wrongdoing and wanting repair.",
"insecure": "Doubting one's worth or acceptance.",
"hesitant": "Holding back due to uncertainty.",
"curious": "Interested and wanting to explore something.",
"grateful": "Feeling appreciation for something received.",
"calm": "Feeling settled and regulated.",
"peaceful": "Experiencing inner quiet and ease.",
"content": "Feeling satisfied with the present moment",
"hopeful": "Feeling optimism about the future",
"relieved": "Feeling tension release after stress",
"connected": "Feeling emotionally close to others",
"supported": "Feeling helped or backed by others"

};